# Generated by Django 6.0.2 on 2026-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_pointslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_party_date',
            field=models.DateField(blank=True, null=True, verbose_name='入党时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
