# Generated by Django 6.0.2 on 2026-04-30 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_userprofile_birthday_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(blank=True, max_length=20, null=True, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯')),
                ('class_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='班级/部门')),
                ('app_submit_time', models.DateField(blank=True, null=True, verbose_name='递交入党申请书时间')),
                ('app_talk_time', models.DateField(blank=True, null=True, verbose_name='党组织派人谈话时间')),
                ('app_talker', models.CharField(blank=True, max_length=50, null=True, verbose_name='谈话人')),
                ('activist_recommend_time', models.DateField(blank=True, null=True, verbose_name='优团/党员推荐时间')),
                ('activist_recommend_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐情况')),
                ('activist_confirm_time', models.DateField(blank=True, null=True, verbose_name='确定为积极分子时间')),
                ('activist_vote_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='表决情况')),
                ('activist_public_time', models.DateField(blank=True, null=True, verbose_name='公示时间')),
                ('activist_public_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='公示情况')),
                ('activist_approve_opinion', models.CharField(blank=True, max_length=255, null=True, verbose_name='上级党委审批意见')),
                ('activist_approve_time', models.DateField(blank=True, null=True, verbose_name='审批时间')),
                ('contact1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='培养联系人1姓名')),
                ('contact1_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='培养联系人1电话')),
                ('contact2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='培养联系人2姓名')),
                ('contact2_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='培养联系人2电话')),
                ('target_mass_meeting_time', models.DateField(blank=True, null=True, verbose_name='征求群众意见座谈会时间')),
                ('confirm_target_meeting_time', models.DateField(blank=True, null=True, verbose_name='支委会/大会讨论时间')),
                ('target_public_time', models.DateField(blank=True, null=True, verbose_name='公示时间')),
                ('target_public_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='公示情况')),
                ('target_approve_opinion', models.CharField(blank=True, max_length=255, null=True, verbose_name='上级党委审批意见')),
                ('target_approve_time', models.DateField(blank=True, null=True, verbose_name='审批时间')),
                ('target_train_time', models.DateField(blank=True, null=True, verbose_name='发展对象培训时间')),
                ('target_pol_check', models.CharField(blank=True, choices=[('合格', '合格'), ('不合格', '不合格')], max_length=20, null=True, verbose_name='政审情况')),
                ('probation_pre_check_time', models.DateField(blank=True, null=True, verbose_name='上级党委预审时间')),
                ('probation_train_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='培训情况')),
                ('probation_public_time', models.DateField(blank=True, null=True, verbose_name='拟接收公示时间')),
                ('probation_public_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='公示情况')),
                ('probation_meeting_time', models.DateField(blank=True, null=True, verbose_name='大会讨论接收时间')),
                ('probation_vote_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='表决情况')),
                ('probation_talk_time', models.DateField(blank=True, null=True, verbose_name='上级派人谈话时间')),
                ('probation_talker', models.CharField(blank=True, max_length=50, null=True, verbose_name='谈话人')),
                ('probation_approve_opinion', models.CharField(blank=True, max_length=255, null=True, verbose_name='上级党委审批意见')),
                ('probation_approve_time', models.DateField(blank=True, null=True, verbose_name='审批时间')),
                ('intro1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人1姓名')),
                ('intro1_post', models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人1职务')),
                ('intro1_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='介绍人1电话')),
                ('intro2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人2姓名')),
                ('intro2_post', models.CharField(blank=True, max_length=50, null=True, verbose_name='介绍人2职务')),
                ('intro2_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='介绍人2电话')),
                ('regular_apply_time', models.DateField(blank=True, null=True, verbose_name='转正申请时间')),
                ('regular_mass_meeting_time', models.DateField(blank=True, null=True, verbose_name='转正征求群众意见时间')),
                ('regular_public_time', models.DateField(blank=True, null=True, verbose_name='转正公示时间')),
                ('regular_public_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='公示情况')),
                ('regular_meeting_time', models.DateField(blank=True, null=True, verbose_name='支部大会讨论时间')),
                ('regular_vote_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='表决情况')),
                ('regular_approve_opinion', models.CharField(blank=True, max_length=255, null=True, verbose_name='上级党委审批意见')),
                ('regular_approve_time', models.DateField(blank=True, null=True, verbose_name='审批时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='development_record', to=settings.AUTH_USER_MODEL, verbose_name='关联党员')),
            ],
            options={
                'verbose_name': '党员发展纪实档案',
                'verbose_name_plural': '党员发展纪实档案',
            },
        ),
    ]
