# Generated by Django 6.0.2 on 2026-05-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_partymemberrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', '一级管理员'), ('branch_admin', '支部管理员'), ('member', '普通党员'), ('probationary_member', '预备党员')], default='member', max_length=20, verbose_name='角色'),
        ),
    ]
