# Generated by Django 6.0.2 on 2026-02-22 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动主题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='practice_covers/', verbose_name='封面')),
                ('content', models.TextField(verbose_name='活动详情')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('capacity', models.IntegerField(default=50, verbose_name='招募人数')),
                ('points_reward', models.IntegerField(default=5, verbose_name='积分奖励')),
                ('status', models.IntegerField(choices=[(0, '报名中'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.organization', verbose_name='所属支部')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '报名成功'), (2, '已驳回'), (3, '已签到')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='practice.practiceactivity')),
            ],
            options={
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
