# Generated by Django 6.0.2 on 2026-02-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceactivity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organization', verbose_name='所属支部'),
        ),
    ]
