# Generated by Django 6.0.2 on 2026-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practiceactivity_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysignup',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已驳回'), (3, '已发分')], default=0),
        ),
    ]
