# Generated by Django 6.0.2 on 2026-02-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('video_url', models.URLField(max_length=500, verbose_name='视频链接')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='课程封面')),
                ('points_reward', models.IntegerField(default=10, verbose_name='奖励积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organization', verbose_name='所属组织(仅本组织可见)')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '课程管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='已看时长(秒)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('feedback', models.TextField(blank=True, verbose_name='心得体会')),
                ('last_studied_at', models.DateTimeField(auto_now=True, verbose_name='最后学习时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学习人')),
            ],
            options={
                'verbose_name': '学习记录',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
