# Generated by Django 6.0.2 on 2026-02-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('system', '0002_pointslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, verbose_name='图文内容/练习题'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(1, '视频课程'), (2, '图文/练习题')], default=1, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='视频链接'),
        ),
    ]
