# Generated by Django 6.0.2 on 2026-02-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_course_content_course_course_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题干')),
                ('q_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题')], default='single', max_length=10, verbose_name='题目类型')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='题目解析')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '习题',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否为正确答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question')),
            ],
            options={
                'verbose_name': '选项',
            },
        ),
    ]
