# Generated by Django 6.0.2 on 2026-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='是否必修'),
        ),
    ]
