# Generated by Django 6.0.2 on 2026-02-18 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面')),
                ('content', models.TextField(verbose_name='内容')),
                ('article_type', models.IntegerField(choices=[(1, '今日时政'), (2, '通知公告'), (3, '党员风采'), (4, '支部动态')], default=1, verbose_name='类型')),
                ('status', models.IntegerField(choices=[(0, '草稿'), (1, '已发布')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '文章管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
