# Generated by Django 6.0.2 on 2026-02-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, '时政要闻'), (2, '通知公告'), (3, '党员风采'), (4, '支部动态'), (5, '学习园地'), (6, '实践中心')], default=1, verbose_name='类型'),
        ),
    ]
