# Generated by Django 6.0.2 on 2026-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='摘要'),
        ),
    ]
