# Generated by Django 6.0.2 on 2026-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, '党建动态'), (2, '通知公告'), (3, '风采展示'), (4, '理论文章'), (5, '学习天地'), (6, '实践纪实'), (7, '支部实践成果')], default=1, verbose_name='类型'),
        ),
    ]
